.Dd April 9, 2015
.Dt cpath 1
.Os Darwin
.Sh NAME
.Nm cpath
.Nd copy the current working directory path to the MacOS clipboard
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
will copy the path returned by the getcwd() function into the MacOS clipboard.  It
is more convenient than:
.Pp
.Dl pwd | pbcopy
.Pp
because it doesn't copy any newline character, which means you can paste the copied
path into a terminal application without trying to execute it.
.Sh FILES
.Bl -tag -width "/usr/local/bin/cpath" -compact
.It Pa /usr/local/bin/cpath
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
