#!/usr/bin/perl

print "'osxutils' is a collection of MacOS command line utilities. The programs are listed in alphabetical order, followed by a short description of their function. For more detail on the functionality of individual tools, refer to their individual man pages.\n\n";

print "cpath        copy the current working directory to the clipboard\n";
print "finfo        print information about a file in a style similar to the Mac OS X Finder\n";
print "getfcomment  print a file's Spotlight comment\n";
print "geticon      extract a file's icon as an image\n";
print "getvolume    show the global system volume setting\n";
print "google       search Google in default browser\n";
print "hfsdata      print a file's HFS- or Mac-specific metadata\n";
print "lsmac        list directory contents with OS X metadata\n";
print "mkalias      create OS X Finder aliases\n";
print "rcmac        recursively list files (like lsmac)\n";
print "setfcomment  set a file's Spotlight comments\n";
print "setfctypes   set heritage OS X File Type or Creator of a file\n";
print "setfflags    set a file's Finder flags\n";
print "seticon      set a file's OS X Icon\n";
print "setlabel     set a file's Finder Label\n";
print "setsuffix    batch modify file suffices\n";
print "setvolume    set the global system volume\n";
print "mvtrash      move a file to the Trash\n";
print "wikipedia    search Wikipedia in default browser\n";
print "wsupdate     update the Finder filesystem display\n";
print "\n";
