.Dd April 9, 2015
.Dt wsupdate 1
.Os Darwin
.Sh NAME
.Nm wsupdate
.Nd report file system change to Mac OS X
.Sh SYNOPSIS
.Nm
.Ar [-vh]
.Ar
.Sh DESCRIPTION
.Ar wsupdate
is a simple command line tool to execute the NSWorkspace method 'noteFileSystemChanged'.  This will make the Finder update its open windows.  If no arguments are given, the system will receive a general notification.  If files are specified, these particular locations will be updated.
.Sh FILES
.Bl -tag -width "/usr/local/bin/wsupdate" -compact
.It Pa /usr/local/bin/wsupdate
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
