#!/usr/bin/perl

if ($ARGV[0] =~ m/-\w*h/ or $ARGV[0] eq "")
{
	printf("Usage: setvolume [1-100]\n");
	exit(64);
}

$vol = $ARGV[0];
system("/usr/bin/osascript -e 'set volume output volume $vol'");
exit(0);
