.Dd Tue Apr 01 2003
.Dt setvolume 1
.Os Darwin
.Sh NAME
.Nm setvolume
.Nd Sets global Mac OS X sound output volume
.Sh SYNOPSIS             
.Nm
[0-100]
.Sh DESCRIPTION
.Nm
is a command line tool for controlling the global Mac OS X sound output voluem.  It accepts a single number, from 0 (silent) to 100 (maximum volume).
.Sh FILES
.Bl -tag -width "/usr/local/bin/setvolume" -compact
.It Pa /usr/local/bin/setvolume
.El
.Sh SEE ALSO 
.Xr lsmac 1 ,
.Xr setfctypes 1 ,
.Xr setfflags 1 ,
.Xr mkalias 1 ,
.Xr setsuffix 1 ,
.Xr SetFile 1 ,
.Xr setfcomment 1 ,
.Xr wsupdate 1, 
.Xr seticon 1,
.Xr geticon 1