.Dd April 9, 2015
.Dt fileinfo 1
.Os Darwin
.Sh NAME
.Nm fileinfo
.Nd print information about a file in a style similar to the Mac OS X Finder
.Sh SYNOPSIS
.Nm
.Op Fl vh
.Op Ar
.Sh DESCRIPTION
.Nm
is a program for printing all sorts of information about a file in a style similar to the
Mac OS X Finder Get Info window.  It lists all sorts of Mac OS-specific metadata information.
.Pp
A list of flags accepted by fileinfo and their descriptions:
.Bl -tag -width -indent
.It Fl v
Prints program version
.It Fl h
Prints a short usage help string
.El
.Pp
.Sh FILES
.Bl -tag -width "/usr/local/bin/fileinfo" -compact
.It Pa /usr/local/bin/fileinfo
.El
.Sh SEE ALSO
.Xr lsmac 1 ,
.Xr setfflags 1 ,
.Xr seticon 1 ,
.Xr geticon 1 ,
.Xr setfctypes 1 ,
.Xr setfcomment 1 ,
.Xr setlabel 1
