.Dd Wed Mar 31 2003               \" DATE 
.Dt setfcomment 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm setfcomment
.Nd set MacOS Finder comments of files and folders.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl vhns
.Op Fl c comment
.Ar file ...
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Ar setfcomment
is a utility for setting MacOS Finder comments of files and folders.  This is done
by sending the MacOS X Finder the appropriate type of Apple Event, or if MacOS 9
Finder comment setting is enabled, by modifying the Desktop Database file using
File Manager APIs.  Typical would usage would be:
.Bl -tag -width -indent  
.It setfcomment -c 'This is my comment' myfile.txt
.El                      \" Ends the list
.Pp
The following options are supported:
.Pp
.Bl -tag -width indent  \" Differs from above in tag removed 
.It Fl c [comment]
Specifies the string you wish to set as Finder comment.  This parameter is required.
.It Fl n
Omit setting MacOS 9 Finder comment.  If this flag is set, the comments set with
.Nm
will not be visible in the MacOS 9 Finder.
.It Fl s
Silent mode.
.Nm
sends no output to STDOUT confirming that the comment for each input file has been successfully set.
.It Fl v
Prints version and author and then exits
.It Fl h
Prints help
.El
.Pp
Please direct queries to Sveinbjorn Thordarson <sveinbt@hi.is>.
.Pp                
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/usr/local/bin/setfcomment" -compact
.It Pa /usr/local/bin/setfcomment
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr SetFile 1 ,
.Xr GetFileInfo 1 ,
.Xr setlabel 1 ,
.Xr seticon 1 ,
.Xr setfflags 1 ,
.Xr setsuffix 1
.Xr lsmac 1 ,