.Dd April 9, 2015
.Dt setfcomment 1
.Os Darwin
.Sh NAME
.Nm setfcomment
.Nd set MacOS Finder comments of files and folders
.Sh SYNOPSIS
.Nm
.Op Fl vhns
.Fl c Ar comment
.Ar
.Sh DESCRIPTION
.Ar setfcomment
is a utility for setting MacOS Finder comments of files and folders.  This is done
by sending Finder the appropriate type of Apple Event, or if MacOS 9
Finder comment setting is enabled, by modifying the Desktop Database file using
File Manager APIs.  Typical usage would be:
.Pp
.Dl setfcomment -c 'This is my comment' myfile.txt
.Pp
.Pp
The following options are supported:
.Pp
.Bl -tag -width indent
.It Fl c Ar comment
Specify the string you wish to set as Finder comment.  This parameter is required.
.It Fl n
Omit setting MacOS 9 Finder comment.  If this flag is set, the comments set with
.Nm
will not be visible in the MacOS 9 Finder.
.It Fl s
Silent mode.  Send no output to STDOUT confirming that the comment for each input file has been successfully set.
.It Fl v
Print version and exit.
.It Fl h
Print usage and exit.
.El
.Sh FILES
.Bl -tag -width "/usr/local/bin/setfcomment" -compact
.It Pa /usr/local/bin/setfcomment
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
.Sh SEE ALSO
.Xr getfcomment 1 ,
.Xr SetFile 1 ,
.Xr setlabel 1 ,
.Xr setfctypes 1 ,
.Xr setfflags 1 ,
.Xr fileinfo 1
