.Dd April 9, 2015
.Dt geticon 1
.Os Darwin
.Sh NAME
.Nm geticon
.Nd extract the icon from a Mac OS X file or folder
.Sh SYNOPSIS
.Nm
.Op Fl vh
.Op Fl t Ar type
.Op Fl o Ar outputfile
.Ar file
.Sh DESCRIPTION
.Nm
is a command line utility for extracting the icon from a Mac OS X file or folder.
The default behaviour is to extract the icon to the current working directory in \.icns format.
This can be overridden using the -t and -o options described below.
.Pp
A list of flags and their descriptions:
.Bl -tag -width -indent
.It Fl o
Specify a path where the icon file will be written.
.It Fl t
Specify what format you want to extract the icon as.  Valid values are icns, png, gif, tiff and jpeg.
.It Fl v
Print version and author.
.It Fl h
Print help/usage.
.El
.Pp
.Sh FILES
.Bl -tag -width "/usr/local/bin/geticon" -compact
.It Pa /usr/local/bin/geticon
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
.Sh SEE ALSO
.Xr seticon 1
