.Dd April 9, 2015
.Dt setfctypes 1
.Os Darwin
.Sh NAME
.Nm setfctypes
.Nd set heritage MacOS File and Creator types
.Sh SYNOPSIS
.Nm
.Op Fl vhs
.Op Fl f filetype
.Op Fl c creator
.Ar
.Sh DESCRIPTION
.Ar setfctypes
is a utility for setting the heritage MacOS File Type and Creator Type of files.  It's very simple to use and is about
twice as fast as Apple's SetFile(1) command.  An example of typical usage would be:
.Bl -tag -width -indent
.It setfctypes -f TEXT -c ttxt myfile.txt
.El
.Pp
It is not neccesary to specify both the -f and -c options.
.Pp
.Ar setfctypes
accepts the following options:
.Pp
.Bl -tag -width indent
.It Fl v
Print version and author and then exit.
.It Fl h
Print help.
.It Fl s
Silent mode.  No errors or problems are reported.
.It Fl c
Followed by a four character string specifying Creator type.
.It Fl f
Followed by a four character string specifying File type.
.El
.Sh FILES
.Bl -tag -width "/usr/local/bin/setfctypes" -compact
.It Pa /usr/local/bin/setfctypes
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
.Sh SEE ALSO
.Xr lsmac 1 ,
.Xr SetFile 1 ,
.Xr GetFileInfo 1 ,
.Xr setlabel 1 ,
.Xr seticon 1 ,
.Xr setfcomment 1 ,
.Xr setfflags 1 ,
.Xr setsuffix 1
