.Dd September 20, 2017
.Dt setfctypes 1
.Os Darwin
.Sh NAME
.Nm setfctypes
.Nd set heritage MacOS File and Creator types
.Sh SYNOPSIS
.Nm
.Op Fl hsv
.Op Fl f Ar filetype
.Op Fl c Ar creator
.Ar
.Sh DESCRIPTION
.Nm
is a utility for setting the heritage MacOS File Type and Creator Type of files.  It's very simple to use and is about
twice as fast as Apple's
.Xr SetFile 1
command.  An example of typical usage would be:
.Pp
.Dl setfctypes -f TEXT -c ttxt myfile.txt
.Pp
It is not neccesary to specify both the -f and -c options.
.Pp
.Nm
accepts the following options:
.Pp
.Bl -tag -width indent
.It Fl c Ar creator
Specify four character Creator type.
.It Fl f Ar filetype
Specify four character File type.
.It Fl h
Print usage and exit.
.It Fl s
Silent mode.  No errors or problems are reported.
.It Fl v
Print version and exit.
.El
.Sh FILES
.Bl -tag -width "/usr/local/bin/setfctypes" -compact
.It Pa /usr/local/bin/setfctypes
.Sh AUTHOR
Originally written by
.An Sveinbjorn Thordarson Aq sveinbjornt@gmail.com .
.Sh SEE ALSO
.Xr SetFile 1 ,
.Xr setlabel 1 ,
.Xr setfcomment 1 ,
.Xr setfflags 1 ,
.Xr finfo 1
