.Dd Tue Apr 01 2003
.Dt wiki 1
.Os Darwin
.Sh NAME
.Nm wiki
.Nd search Wikipedia from the command line
.Sh SYNOPSIS             
.Nm 
[search words] [...]
.Sh DESCRIPTION
.Nm
is a command line program to search the Wikipedia.  All arguments following the command will be counted as search terms.  A browser window will open with the relevant Wikipedia results.           
.Sh FILES               
.Bl -tag -width "/usr/local/bin/wiki" -compact
.It Pa /usr/local/bin/wiki
.El
.Sh SEE ALSO 
.Xr google 1