.Dd April 9, 2015
.Dt setlabel 1
.Os Darwin
.Sh NAME
.Nm setlabel
.Nd set MacOS Finder label of files and folders
.Sh SYNOPSIS
.Nm
.Op Fl vhs
.Ar Label file ...
.Sh DESCRIPTION
.Ar setlabel
is a utility for setting the MacOS Finder label of files and folders.  This is done
by modifying the meta-data flag fields in the HFS file record.  The available labels
(case sensitive) are:
.Pp
None,
Red,
Orange,
Yellow,
Green,
Blue,
Purple,
Gray
.Pp
An example of typical usage would be:
.Bl -tag -width -indent
.It setlabel Gray myfile.txt
.El
.Pp
The following options are supported:
.Pp
.Bl -tag -width indent
.It Fl v
Prints version and author and then exits
.It Fl h
Prints help
.It Fl s
Silent mode.  No output list or error reports are printed.
.El
.Pp
Please direct queries to Sveinbjorn Thordarson <sveinbt@hi.is>.
.Sh FILES
.Bl -tag -width "/usr/local/bin/setlabel" -compact
.It Pa /usr/local/bin/setlabel
.El
.Sh SEE ALSO
.Xr SetFile 1 ,
.Xr GetFileInfo 1 ,
.Xr setfflags 1 ,
.Xr setsuffix 1
.Xr lsmac 1 ,
.Xr setfcomment 1 ,
.Xr setfctypes 1
