.Dd April 9, 2015
.Dt seticon 1
.Os Darwin
.Sh NAME
.Nm seticon
.Nd set icon of Mac OS X files
.Sh SYNOPSIS
.Nm
.Op Fl vhd
.Ar source
.Ar
.Sh DESCRIPTION
.Nm
is a utility for setting a custom icon on Mac OS X files and folders via the command line.
The first argument to seticon is the source file, i.e. the file with the icon you wish to
apply to other file(s).  Any arguments after the first should be files which you wish to
give the custom icon to.
.Pp
Please note that this need not be an .icns file -- see the -d option for using
an .icns file as a source.
.Nm
defaults to retrieving the actual icon of the file in question.
.Pp
Typical usage would look like this:
.Pp
.Dl seticon sourcefile file1 file2
.Pp
The example above would result in the icon of
.Ar sourcefile
being applied to the files
.Ar file1
and
.Ar file2
as custom icons.
.Pp
.Nm
supports the following options:
.Bl -tag -width indent
.It Fl d
Use the data of the source file as icon instead of the source file's actual icon.
.It Fl v
Print version and exit.
.It Fl h
Print usage and exit.
.El
.Sh FILES
.Bl -tag -width "/usr/local/bin/seticon" -compact
.It Pa /usr/local/bin/seticon
.Sh AUTHOR
Originally written by
.An Sveinbjorn Thordarson Aq sveinbjornt@gmail.com .
.Sh SEE ALSO
.Xr geticon 1
