.Dd April 9, 2015
.Dt setsuffix 1
.Os Darwin
.Sh NAME
.Nm setsuffix
.Nd set, remove and replace filename suffixes
.Sh SYNOPSIS
.Nm
.Op Fl vhsefar
.Op Fl l Ar length
.Fl x Ar suffix
.Ar
.Sh DESCRIPTION
.Nm
can be used to set, change and remove filename suffixes.  Suffixes are used by MacOS X to identify
files and determine what application to employ when opening them.
.Pp
.Nm
accepts the following options:
.Bl -tag -width indent
.It Fl x Ar suffix
Specify the suffix you want added, without the leading dot (".")
.It Fl l Ar length
Set the max number of characters that can constitute a valid suffix.
.Nm
defaults to 4, so without this specification it will ignore all suffixes longer than 4 characters.
.It Fl s
Silent mode.  Only critical errors or invalid usage errors are printed to stdout.
.It Fl e
Ignore files that already have a suffix.
.It Fl f
Ignore folders.
.It Fl a
Append the new suffix instead of replacing the old one.
.It Fl r
Remove file suffix.  If this option is specified, all other options apart from -l are ignored.
.It Fl v
Print version and exit.
.It Fl h
Print usage and exit.
.El
.Sh FILES
.Bl -tag -width "/usr/local/bin/setsuffix" -compact
.It Pa /usr/local/bin/setsuffix
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
