.Dd April 9, 2015
.Dt rcmac 1
.Os Darwin
.Sh NAME
.Nm rcmac
.Nd recursively list all files in a hierarchy in the style of lsmac
.Sh SYNOPSIS
.Nm
.Ar directory
.Sh DESCRIPTION
.Nm
uses
.Xr lsmac 1
to descend down a directory tree and list every single non-directory file within the structure.  The program accepts only one argument, which should be the path of a directory to descend into.
.Sh FILES
.Bl -tag -width "/usr/local/bin/rcmac" -compact
.It Pa /usr/local/bin/rcmac
.El
.Sh AUTHOR
Originally written by
.An Sveinbjorn Thordarson Aq sveinbjornt@gmail.com .
.Sh SEE ALSO
.Xr lsmac 1
