.Dd April 9, 2015
.Dt rcmac 1
.Os Darwin
.Sh NAME
.Nm rcmac
.Nd recursively list all files in a hierarchy in the style of lsmac
.Sh SYNOPSIS
.Nm
[directory]
.Sh DESCRIPTION
.Nm
descends into directory structures and lists every single non-directory file within the structure in the style of 'lsmac'.  See the lsmac(1) man page for details.  The program accepts only one argument, which must be the path of a directory to descend into.
.Sh FILES
.Bl -tag -width "/usr/local/bin/rcmac" -compact
.It Pa /usr/local/bin/rcmac
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
.Sh SEE ALSO
.Xr lsmac 1
