#!/usr/bin/perl
#
# ©2003 Sveinbjorn Thordarson <sveinbt@hi.is>
# Search google with command line parameters
#

use strict;
use warnings;

my $google_url = "http://www.google.com/search?q=";
my $google_img_url = "http://images.google.com/images?q=";

# Handle image search flag
if (@ARGV && $ARGV[0] eq "-i")
{
    $google_url = $google_img_url;
    shift @ARGV;
}

# Print usage if no search terms given
my $USAGE = <<EOF;
usage: google [-i] searchword ...
EOF
die $USAGE unless @ARGV;

# Create query string to be passed
my $query_string = join '+', @ARGV;

#Replace spaces with plus
$query_string =~ s/ /\+/;

# Pass url to open command, which will open in default browser
exec("open", "$google_url$query_string");
