.Dd April 9, 2015
.Dt google 1
.Os Darwin
.Sh NAME
.Nm google
.Nd launch a Google search from the command line in MacOS X
.Sh SYNOPSIS
.Nm
.Op Fl ih
.Ar searchword ...
.Sh DESCRIPTION
.Nm
is a very small and simple program that enables you to open a browser window with a Google query from the command line.
You can pass the search words as multiple arguments or as a single argument within quotes.
.Pp
An example of typical usage would be:
.Pp
.Dl google learn programming
.Pp
or, alternatively
.Pp
.Dl google 'learn programming'
.Pp
.Nm
supports the following options:
.Bl -tag -width indent
.It Fl i
Search for images.
.It Fl h
Print usage and exit.
.El
.Sh FILES
.Bl -tag -width "/usr/local/bin/google" -compact
.It Pa /usr/local/bin/google
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
.Sh SEE ALSO
.Xr wiki 1
