.Dd April 9, 2015
.Dt getfcomment 1
.Os Darwin
.Sh NAME
.Nm getfcomment
.Nd print Mac OS comment for file
.Sh SYNOPSIS
.Nm
.Op Fl vhpc
.Ar
.Sh DESCRIPTION
.Nm
is a command line program which prints out the Mac OS comment on a file passed as an argument.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl p
Print filename before each comment.
.It Fl c
Output Mac OS Classic Desktop Database comment instead of Mac OS X Finder comment.
.It Fl v
Print version and exit.
.It Fl h
Print usage and exit.
.El
.Pp
.Sh FILES
.Bl -tag -width "/usr/local/bin/getfcomment" -compact
.It Pa /usr/local/bin/getfcomment
.El
.Sh AUTHOR
Originally written by
.An Sveinbjorn Thordarson Aq sveinbjornt@gmail.com .
.Sh SEE ALSO
.Xr setfcomment 1 ,
.Xr fileinfo 1 ,
.Xr hfsdata 1
