.Dd April 9, 2015
.Dt getvolume 1
.Os Darwin
.Sh NAME
.Nm getvolume
.Nd print the global Mac OS X sound output volume setting
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a command line tool for checking the global Mac OS X sound output volume.  It prints an integer in the range [0-100].
.Sh FILES
.Bl -tag -width "/usr/local/bin/getvolume" -compact
.It Pa /usr/local/bin/getvolume
.El
.Sh AUTHOR
Originally written by Sveinbjorn Thordarson <sveinbjornt@gmail.com>.
.Sh SEE ALSO
.Xr setvolume 1
